### ISSUE TITLE
RS007 - Agregar un mecanismo visual para servidor de datos

### ISSUE THREAD

**Issue by cescobarf** [TDiazT/CodingSpectator#21]
Agregar una interfaz gráfica que permita al usuario configurar el servidor de datos hacia donde enviar los datos recolectados

**Comment by TDiazT** [comment]
Iniciación :
- Añadir interfaz para elegir servidor

**Comment by TDiazT** [comment]
Concept Location:
Using grep with the term 'upload', en:
edu.illinois.codingspectator.monitor.ui es encuentra
		- UploadingPreferencePage.java
El cual corresponde a las settings en Eclipse -> Preferences
![codingspectator_preferences](https://cloud.githubusercontent.com/assets/7966908/10648026/7bf1d0d2-7812-11e5-9113-44a88196ca89.png)

**Comment by TDiazT** [comment]
#### Impact Analysis:

![impactanalysis_rs007](https://cloud.githubusercontent.com/assets/7966908/10655735/e4625e1c-784d-11e5-97fe-38d92b9099d7.png)

From the _UploadingPreferencePage_, you can get to the _Submitter_ class through the actionlistener set to the "Upload Button" (in _createUploadNowButton_ method).

Most notably, the Submitter class submits to a repository using _SVN_, through a set of SVNManager classes.

SVNManager calls two other:
- LocalSVNManager
- RemoteSVNManager

In both cases they use the URLManager class which holds the reference to the repository URL. This is set in constructor and retrieved by the PrefsFacade class which itself retrieves it from a properties file (**messages.properties**). 

**Detail:** The repository URL is slightly modified when SVNManagers request it (includes username and UUID)

**Comment by TDiazT** [comment]
#### Steps to change

[] Add text field to preferences
[] Display current production server
    [] Add label to preferences
    [] Fetch current server URL (AuthenticationPrompter_ProductionRepositoryURL)
    [] add server URL to label
[] Display current test server
    [] Add label to preferences
    [] Fetch current server URL (AuthenticationPrompter_TestRepositoryURL)
    [] add server URL to label
[] Store input data in text field
    [] Add apply button to preference page "Uploading"
    [] Add action listener to apply button
        [] Modify messages.properties
            [] add method to Messages class to modify AuthenticationPrompter_ProductionRepositoryURL
            [] add method to Messages class to modify AuthenticationPrompter_TestRepositoryURL

[] Check that input value is properly stored

**Comment by TDiazT** [comment]
#### Possible sub task

During the process of submission it has to authenticate the user, but this may not be necessary depending on the server or maybe it changes from what it is now.

** Might possibly have to add another task regarding this authentication issue **

**Comment by TDiazT** [comment]
As of now, the upload URLs are stored in the Messages class. It appears these values are static, therefore it may be better to move them from Messages to either PrefsFacade or a new Settings class (or maybe later a configuration page?)

These may result in some unexpected changes in some other classes!

**Comment by TDiazT** [comment]
Not sure how to layout the fields in the preference page.

The StringFieldEditor apparently doesn't allow to display values when editable (have to set to not editable in order to display information). This means that either a button or another StringFieldEditor should be added to allow edition of server.

**Comment by TDiazT** [comment]
###Notice

To test the UI using SWTBot, in particular the Preference pages and test setting values to the upload URL fields, there is an issue with Mac OS X. The option is accessible through the menu `Eclipse`, `Preferences` but this menu is not available through SWTBot. 

As far as I've seen, it is a System menu, therefore accesible in other ways. Some is explained in this [link](https://www.eclipse.org/forums/index.php/t/854280/)

Even trying with SWTBot Recorder doesn't recognize the actions taken.
