### ISSUE TITLE
RS010 - Recopilación inicial de plugins instalados

### ISSUE THREAD

**Issue by jawilliam** [TDiazT/CodingSpectator#33]
El sistema debe generar una lista de los plugins instalados en el IDE la primera vez que se inicia.

**Comment by lmun** [comment]
Esta funcionalidad esta implementada en el archivo `PluginList.java` que pertenece al package  `edu.illinois.codingtracker.operations.starts` que genera una lista de todos los plugins instalados en orden alfabético y agrupados por proveedor

**Comment by lmun** [comment]
Tambien La lista de plugins iniciales se guarda en la la clase `MonitorTask.java` que pertenece al package `edu.illinois.codingtracker.listeners` para luego comparar esta lista con la lista de plugins en el momento siguiente en que se ejecute MonitorTask, esta lista no guarda solo los nombres sino tambien los estados en que se encuentran los plugins y no los ordena
