### ISSUE TITLE
RS011 - Inclusión de nuevos plugins instalados

### ISSUE THREAD

**Issue by jawilliam** [TDiazT/CodingSpectator#34]
A través de un mecanismo de listeners el sistema debe poder incluir a la lista inicial de plugins instalados, los nuevos plugins que se instalen.

**Comment by lmun** [comment]
Como comentado en el issue #42 no se usaran listeners, si no que se seguirá verificando cada cierto tiempo los nuevos plugins pero se guardara el timestamp de cuando fue modificado
