### ISSUE TITLE
RU002 Opción de formato de archivos de salida (XML o CSV)

### ISSUE THREAD

**Issue by jawilliam** [TDiazT/CodingSpectator#6]
Permitir al usuario elegir el formato de los archivos de datos de salida, entre XML ó CSV.

**Comment by jawilliam** [comment]
Permitir al usuario elegir el formato de los archivos de datos de salida, entre XML ó CSV.

**Comment by TDiazT** [comment]
Permitir al usuario elegir el formato de los archivos de datos de salida, entre XML ó CSV.

**Comment by TDiazT** [comment]
Requisitos de Software:
- RS0003 #8
