### ISSUE TITLE
RS003 Generación de archivos en formato CSV

### ISSUE THREAD

**Issue by jawilliam** [TDiazT/CodingSpectator#8]
El sistema debe poder generar archivos de datos en formato CSV.

**Comment by TDiazT** [comment]
Buscando en unos commits pillé algo que puede servir para CVS:
[commit con info](https://github.com/karlitrotski/CodingSpectator/commit/17fbdc8852bdb3c1f1c94cc22463e0574d894fba)

En particular, hay una [CVSCommitedFileOperation.java](https://github.com/karlitrotski/CodingSpectator/blob/17fbdc8852bdb3c1f1c94cc22463e0574d894fba/plug-ins/common/edu.illinois.codingtracker.operations/src/edu/illinois/codingtracker/operations/files/snapshoted/CVSCommittedFileOperation.java) 

Aunque no estoy seguro, pero por si acaso

**Comment by TDiazT** [comment]
El primero CVSCommitedFileOperation no tiene nada que ver

**Comment by TDiazT** [comment]
En esta [página](https://github.com/karlitrotski/CodingSpectator/wiki/General-information-about-source-code) de la wiki anterior aparece al final información sobre el proceso de pasar los logs a CSV que quizás te sirva

**Comment by jawilliam** [comment]
Recuerda que el tema de los CSV es de Constanza, yo solo le estoy documentando todo lo que encuentro que pudiese servirle. Salu2
